//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashi.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int id { get; set; }
        public string anh { get; set; }
        public System.DateTime ngay { get; set; }
        public string thongtin1 { get; set; }
        public string mieuta { get; set; }
        public string chitiet { get; set; }
        public string thongtin2 { get; set; }
    }
}
