//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashi.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_categorys { get; set; }
        public string size { get; set; }
        public string ten { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> giaban { get; set; }
        public Nullable<int> giagiam { get; set; }
        public Nullable<int> phantram { get; set; }
        public string mieuta { get; set; }
        public string chitiet { get; set; }
        public string gioithieu { get; set; }
        public string dactrung { get; set; }
        public string anhmh { get; set; }
        public string cannang { get; set; }
        public Nullable<bool> noibat { get; set; }
        public Nullable<bool> spmoi { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
