//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashi.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class slide
    {
        public int id { get; set; }
        public string anh { get; set; }
        public string ten { get; set; }
        public string tensk { get; set; }
        public string chitiet { get; set; }
        public string cuahang { get; set; }
        public string tenchuongtrinh { get; set; }
        public int phantram { get; set; }
    }
}
