//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashi.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class womenbanner
    {
        public int id { get; set; }
        public string anh { get; set; }
        public string sale { get; set; }
        public string link1 { get; set; }
        public string link2 { get; set; }
        public string thaotac { get; set; }
        public string link3 { get; set; }
        public string theloai { get; set; }
        public string link4 { get; set; }
        public string mieuta { get; set; }
        public double giaban { get; set; }
        public double giagiam { get; set; }
    }
}
